- type: web
  name: mineflayer-bot-web
  env: node
  plan: free
  buildCommand: "npm ci"
  startCommand: "npm start"
  repo: https://github.com/Balvinder-ke-code/AlwaysOn-Aternos
  branch: main
  envVars:
    - key: MINECRAFT_HOST
    value: "haklakasmp.aternos.me"
    - key: MINECRAFT_USERNAME
    value: "HaklaTheBot"
